In [32]:
import numpy as np
import pandas as pd

df = pd.read_csv("/Users/shwetakohale/Downloads/email.csv") #loaded the data from a csv file

In [33]:
df.head() #lists out the first 5 entries of the dataset to give you a gist of the data
# df.tail() #similar to df.head but it lists out the LAST 5 rows

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [34]:
df.info() #information about the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5573 entries, 0 to 5572
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5573 non-null   object
 1   Message   5573 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [35]:
df.describe() #descriptive statistics

       Category                 Message
count      5573                    5573
unique        3                    5158
top         ham  Sorry, I'll call later
freq       4825                      30

In [36]:
df.columns #lists all the columns in the dataset

Index(['Category', 'Message'], dtype='object')

In [37]:
df.index

RangeIndex(start=0, stop=5573, step=1)

In [47]:
df["Category"] #Indexing by columns (this is called a series)

0                  ham
1                  ham
2                 spam
3                  ham
4                  ham
             ...
5568               ham
5569               ham
5570               ham
5571               ham
5572    {"mode":"full"
Name: Category, Length: 5572, dtype: object

In [39]:
df.iloc[10] #Indexing by row

Category                                                  ham
Message     I'm gonna be home soon and i don't want to tal...
Name: 10, dtype: object

In [45]:
df[(df["Category"] == "ham")] #filtering

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
6         ham  Even my brother is not like to speak with me. ...
...       ...                                                ...
5565      ham                                       Huh y lei...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[4824 rows x 2 columns]

In [56]:
df["Message"] = df["Message"].str.upper() #Updating a column

In [28]:
#df.loc() -> used to locate at what index the data is in

In [54]:
df = df.drop(25) #deletes row 25

In [55]:
df.to_csv("new_file.csv", index=False)